routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/



/*Site*/
Route::get('/',['as' => 'index', 'uses' => 'SiteController@index']);

Route::group(['as' => 'site.'], function(){
    Route::get('index',['as' => 'index', 'uses' => 'SiteController@index']);
    Route::get('sobre',['as' => 'sobre', 'uses' => 'SiteController@sobre']);
    Route::get('artigos',['as' => 'artigos', 'uses' => 'SiteController@artigos']);
    Route::get('artigo/{slug}',['as' => 'artigo', 'uses' => 'SiteController@artigo']);
    Route::get('contato',['as' => 'contato', 'uses' => 'SiteController@contato']);
    Route::post('contato_enviar',['as' => 'contato_enviar', 'uses' => 'SiteController@contato_enviar']);
    Route::get('nossos_gatos',['as' => 'nossos_gatos', 'uses' => 'SiteController@nossos_gatos']);
    Route::get('disponiveis',['as' => 'disponiveis', 'uses' => 'SiteController@disponiveis']);
    Route::get('videos',['as' => 'videos', 'uses' => 'SiteController@videos']);
    Route::get('acfe',['as' => 'acfe', 'uses' => 'SiteController@acfe']);

    Route::get('login',['as' => 'login', 'uses' => 'SiteController@login']);
    Route::get('logout',['as' => 'logout', 'uses' => 'SiteController@logout']);

    Route::get('teste',['as' => 'teste', 'uses' => 'SiteController@teste']);
});

/*Admin*/
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['web','auth']], function(){
    Route::get('/',['as' => 'index', 'uses' => 'AdminHomeController@index']);
    Route::get('home',['as' => 'home', 'uses' => 'AdminHomeController@index']);

    Route::get('banners',['as' => 'banners.index', 'uses' => 'AdminBannersController@index']);
    Route::get('banners/novo',['as' => 'banners.novo', 'uses' => 'AdminBannersController@novo']);
    Route::get('banners/editar/{id}',['as' => 'banners.editar', 'uses' => 'AdminBannersController@editar']);
    Route::post('banners/salvar',['as' => 'banners.salvar', 'uses' => 'AdminBannersController@salvar']);
    Route::post('banners/atualizar/{id}',['as' => 'banners.atualizar', 'uses' => 'AdminBannersController@atualizar']);

    Route::get('fotos_categorias',['as' => 'fotos_categorias.index', 'uses' => 'AdminFotosCategoriasController@index']);
    Route::get('fotos_categorias/novo',['as' => 'fotos_categorias.novo', 'uses' => 'AdminFotosCategoriasController@novo']);
    Route::get('fotos_categorias/editar/{id}',['as' => 'fotos_categorias.editar', 'uses' => 'AdminFotosCategoriasController@editar']);
    Route::post('fotos_categorias/salvar',['as' => 'fotos_categorias.salvar', 'uses' => 'AdminFotosCategoriasController@salvar']);
    Route::post('fotos_categorias/atualizar/{id}',['as' => 'fotos_categorias.atualizar', 'uses' => 'AdminFotosCategoriasController@atualizar']);
    Route::get('fotos_categorias/delete/{id}',['as' => 'fotos_categorias.delete', 'uses' => 'AdminFotosCategoriasController@delete']);

    Route::get('fotos/{foto_categoria_id}',['as' => 'fotos.index', 'uses' => 'AdminFotosController@index']);
    Route::get('fotos/novo/{foto_categoria_id}',['as' => 'fotos.novo', 'uses' => 'AdminFotosController@novo']);
    Route::get('fotos/novo2/{foto_categoria_id}',['as' => 'fotos.novo2', 'uses' => 'AdminFotosController@novo2']);
    Route::get('fotos/editar/{id}',['as' => 'fotos.editar', 'uses' => 'AdminFotosController@editar']);
    Route::post('fotos/salvar/{foto_categoria_id}',['as' => 'fotos.salvar', 'uses' => 'AdminFotosController@salvar']);
    Route::post('fotos/salvar2/{foto_categoria_id}',['as' => 'fotos.salvar2', 'uses' => 'AdminFotosController@salvar2']);
    Route::post('fotos/atualizar/{id}',['as' => 'fotos.atualizar', 'uses' => 'AdminFotosController@atualizar']);
    Route::get('fotos/delete/{id}',['as' => 'fotos.delete', 'uses' => 'AdminFotosController@delete']);

    Route::get('artigos',['as' => 'artigos.index', 'uses' => 'AdminNoticiasController@index']);
    Route::get('artigos/novo',['as' => 'artigos.novo', 'uses' => 'AdminNoticiasController@novo']);
    Route::get('artigos/editar/{id}',['as' => 'artigos.editar', 'uses' => 'AdminNoticiasController@editar']);
    Route::post('artigos/salvar',['as' => 'artigos.salvar', 'uses' => 'AdminNoticiasController@salvar']);
    Route::post('artigos/atualizar/{id}',['as' => 'artigos.atualizar', 'uses' => 'AdminNoticiasController@atualizar']);
    Route::get('artigos/delete/{id}',['as' => 'artigos.delete', 'uses' => 'AdminNoticiasController@delete']);

    Route::get('paginas',['as' => 'paginas.index', 'uses' => 'AdminPaginasController@index']);
    Route::get('paginas/novo',['as' => 'paginas.novo', 'uses' => 'AdminPaginasController@novo']);
    Route::get('paginas/editar/{id}',['as' => 'paginas.editar', 'uses' => 'AdminPaginasController@editar']);
    Route::post('paginas/salvar',['as' => 'paginas.salvar', 'uses' => 'AdminPaginasController@salvar']);
    Route::post('paginas/atualizar/{id}',['as' => 'paginas.atualizar', 'uses' => 'AdminPaginasController@atualizar']);
    Route::get('paginas/delete/{id}',['as' => 'paginas.delete', 'uses' => 'AdminPaginasController@delete']);

    Route::get('paginas_textos/{pagina_id}',['as' => 'paginas_textos.index', 'uses' => 'AdminPaginasTextosController@index']);
    Route::get('paginas_textos/novo/{pagina_id}',['as' => 'paginas_textos.novo', 'uses' => 'AdminPaginasTextosController@novo']);
    Route::get('paginas_textos/editar/{id}',['as' => 'paginas_textos.editar', 'uses' => 'AdminPaginasTextosController@editar']);
    Route::post('paginas_textos/salvar/{pagina_id}',['as' => 'paginas_textos.salvar', 'uses' => 'AdminPaginasTextosController@salvar']);
    Route::post('paginas_textos/atualizar/{id}',['as' => 'paginas_textos.atualizar', 'uses' => 'AdminPaginasTextosController@atualizar']);
    Route::get('paginas_textos/delete/{id}',['as' => 'paginas_textos.delete', 'uses' => 'AdminPaginasTextosController@delete']);

    Route::get('colaboradores',['as' => 'colaboradores.index', 'uses' => 'AdminColaboradoresController@index']);
    Route::get('colaboradores/novo',['as' => 'colaboradores.novo', 'uses' => 'AdminColaboradoresController@novo']);
    Route::get('colaboradores/editar/{id}',['as' => 'colaboradores.editar', 'uses' => 'AdminColaboradoresController@editar']);
    Route::post('colaboradores/salvar',['as' => 'colaboradores.salvar', 'uses' => 'AdminColaboradoresController@salvar']);
    Route::post('colaboradores/atualizar/{id}',['as' => 'colaboradores.atualizar', 'uses' => 'AdminColaboradoresController@atualizar']);
    Route::get('colaboradores/delete/{id}',['as' => 'colaboradores.delete', 'uses' => 'AdminColaboradoresController@delete']);

    Route::get('depoimentos',['as' => 'depoimentos.index', 'uses' => 'AdminDepoimentosController@index']);
    Route::get('depoimentos/novo',['as' => 'depoimentos.novo', 'uses' => 'AdminDepoimentosController@novo']);
    Route::get('depoimentos/editar/{id}',['as' => 'depoimentos.editar', 'uses' => 'AdminDepoimentosController@editar']);
    Route::post('depoimentos/salvar',['as' => 'depoimentos.salvar', 'uses' => 'AdminDepoimentosController@salvar']);
    Route::post('depoimentos/atualizar/{id}',['as' => 'depoimentos.atualizar', 'uses' => 'AdminDepoimentosController@atualizar']);
    Route::get('depoimentos/delete/{id}',['as' => 'depoimentos.delete', 'uses' => 'AdminDepoimentosController@delete']);

    Route::get('users',['as' => 'users.index', 'uses' => 'AdminUsersController@index']);
    Route::get('users/novo',['as' => 'users.novo', 'uses' => 'AdminUsersController@novo']);
    Route::get('users/editar/{id}',['as' => 'users.editar', 'uses' => 'AdminUsersController@editar']);
    Route::post('users/salvar',['as' => 'users.salvar', 'uses' => 'AdminUsersController@salvar']);
    Route::post('users/atualizar/{id}',['as' => 'users.atualizar', 'uses' => 'AdminUsersController@atualizar']);
    Route::get('users/senha_editar/{id}',['as' => 'users.senha_editar', 'uses' => 'AdminUsersController@senha_editar']);
    Route::post('users/senha_atualizar/{id}',['as' => 'users.senha_atualizar', 'uses' => 'AdminUsersController@senha_atualizar']);
    Route::get('users/delete/{id}',['as' => 'users.delete', 'uses' => 'AdminUsersController@delete']);
});

/*Auth*/
Route::group(['prefix' => 'auth', 'as' => 'auth.','middleware' => ['web']], function() {
    Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
    Route::post('login', ['as' => 'login.post', 'uses' => 'Auth\LoginController@login']);
    Route::get('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);
});

/*Exibe as SQL's executadas*/
#Event::listen('Illuminate\Database\Events\QueryExecuted', function ($query) {var_dump($query->sql);var_dump($query->bindings);var_dump($query->time);});

resources/views/admin.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="robots" content="noindex,nofollow">
    <title>Gatil Neway Painel</title>

    <!--CSS-->
    <link rel="stylesheet" href="{{URL::asset('css/bootstrap.css')}}" >
    <link rel="stylesheet" href="{{URL::asset('css/style.css')}}">
    <link rel="stylesheet" href="{{URL::asset('fonts/font-awesome.css')}}">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{{URL::asset('css/ie10-viewport-bug-workaround.css')}}" rel="stylesheet">

    <script src="{{URL::asset('js/ie-emulation-modes-warning.js')}}"></script>
    <!--[if lt IE 9]><script src="{{URL::asset('js/ie8-responsive-file-warning.js')}}"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="{{URL::asset('js/html5shiv.js')}}"></script>
    <script src="{{URL::asset('js/respond.min.js')}}"></script>
    <![endif]-->
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">
                <img src="{{URL::asset('img/logo.png')}}" alt="" height="50">
            </a>
        </div>

        <div class="collapse navbar-collapse" id="navbar">
            <ul class="nav navbar-nav">
                @if(!empty(Auth::user()))
                    <li><a href="{{ route('admin.home') }}">Home</a></li>
                    <li><a href="{{ route('admin.paginas.index') }}">Páginas e Textos</a></li>
                    <li><a href="{{ route('admin.banners.index') }}">Banners</a></li>
                    <li><a href="{{ route('admin.fotos_categorias.index') }}">Fotos</a></li>
                    <li><a href="{{ route('admin.fotos.index',['foto_categoria_id' => 12]) }}">Vídeos</a></li>
                    <li><a href="{{ route('admin.artigos.index') }}">Artigos</a></li>
                    <li><a href="{{ route('admin.colaboradores.index') }}">Colaboradores</a></li>
                    <li><a href="{{ route('admin.depoimentos.index') }}">Depoimentos</a></li>
                    <li><a href="{{ route('admin.users.index') }}">Usuários</a></li>
                @endif
            </ul>

            <ul class="nav navbar-nav navbar-right">
                @if(auth()->guest())
                    @if(!Request::is('auth/login'))
                        <li><a href="{{ url('/auth/login') }}">Entrar</a></li>
                    @endif
                @else
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-expanded="false">{{ auth()->user()->name }} <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{{ url('/auth/logout') }}">Sair</a></li>
                        </ul>
                    </li>
                @endif
            </ul>
        </div>
    </div>
</nav>

@yield('content')

<!--JS-->
<script src="{{URL::asset('js/jquery.js')}}"></script>
<script src="{{URL::asset('js/jquery-migrate-1.2.1.min.js')}}"></script>
<script src="{{URL::asset('js/superfish.js')}}"></script>
<script src="{{URL::asset('js/jquery.easing.1.3.js')}}"></script>
<script src="{{URL::asset('js/jquery.mobilemenu.js')}}"></script>
<script src="{{URL::asset('js/jquery.ui.totop.js')}}"></script>
<script src="{{URL::asset('js/jquery.equalheights.js')}}"></script>
<script src="{{URL::asset('js/bootstrap.min.js')}}"></script>
<script src="{{URL::asset('js/tm-scripts.js')}}"></script>
@yield('scripts')
</body>
</html>

resources/views/home.blade.php
@extends('admin')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Painel</div>

                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="botoes-home">
                                    <a href="{{ route('admin.paginas.index') }}" class="btn btn-default btn-lg">
                                        <i class="fa fa-file-text" aria-hidden="true"></i><br>
                                        Páginas
                                    </a>
                                    <a href="{{ route('admin.banners.index') }}" class="btn btn-default btn-lg">
                                        <i class="fa fa-picture-o" aria-hidden="true"></i><br>
                                        Banners
                                    </a>
                                    <a href="{{ route('admin.fotos_categorias.index') }}" class="btn btn-default btn-lg">
                                        <i class="fa fa-camera" aria-hidden="true"></i><br>
                                        Fotos
                                    </a>
                                    <a href="{{ route('admin.fotos.index',['foto_categoria_id' => 12]) }}" class="btn btn-default btn-lg">
                                        <i class="fa fa-youtube-square" aria-hidden="true"></i><br>
                                        Vídeos
                                    </a>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="botoes-home">
                                    <a href="{{ route('admin.artigos.index') }}" class="btn btn-default btn-lg">
                                        <i class="fa fa-comments-o" aria-hidden="true"></i><br>
                                        Artigos
                                    </a>
                                    <a href="{{ route('admin.colaboradores.index') }}" class="btn btn-default btn-lg">
                                        <i class="fa fa-child" aria-hidden="true"></i><br>
                                        Colaboradores
                                    </a>
                                    <a href="{{ route('admin.depoimentos.index') }}" class="btn btn-default btn-lg">
                                        <i class="fa fa-list" aria-hidden="true"></i><br>
                                        Depoimentos
                                    </a>
                                    <a href="{{ route('admin.users.index') }}" class="btn btn-default btn-lg">
                                        <i class="fa fa-users" aria-hidden="true"></i><br>
                                        Usuários
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-85305439-1"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-85305439-1');
    </script>
    <title>Gatil Neway - Gatos Persas, Himalaias e Exóticos</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="content-language" content="pt-br">
    <link rel="icon" href="{{URL::asset('img/favicon.ico')}}" type="image/x-icon">
    <link rel="shortcut icon" href="{{URL::asset('img/favicon.ico')}}" type="image/x-icon" />
    <meta name="keywords" content="gatil, gato, gatil neway, gatos de raça, filhote de gato, filhote de gato persa, gatos da raça persa, gato persa, gato himalaio, gato exótico, criador de gatos, filhote, gatinho, criador de gato em ES, criador, felinos, gato persa Vitória ES, gato persa Espírito Santo">
    <meta name="description" content="Gatil Neway - Especializado em Persas, Himalaias e Exóticos, localizado em  Vitória - ES.">
    <meta name="author" content="Raphael Lorencini">
    <meta name="format-detection" content="telephone=no" />
    <meta name="robots" content="index,follow">

    <!--CSS-->
    <link rel="stylesheet" href="{{URL::asset('css/bootstrap.css')}}" >
    <link rel="stylesheet" href="{{URL::asset('css/style.css')}}">
    <link rel="stylesheet" href="{{URL::asset('fonts/font-awesome.css')}}">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{{URL::asset('css/ie10-viewport-bug-workaround.css')}}" rel="stylesheet">

    <script src="{{URL::asset('js/ie-emulation-modes-warning.js')}}"></script>
    <!--[if lt IE 9]><script src="{{URL::asset('js/ie8-responsive-file-warning.js')}}"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="{{URL::asset('js/html5shiv.js')}}"></script>
    <script src="{{URL::asset('js/respond.min.js')}}"></script>
    <![endif]-->
</head>
<body>
@include('menu')

@yield('content')

<!--footer-->
<div class="container">
    <footer>
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 rodape1">
                <p>
                    <img src="{{URL::asset('img/foo_logo2.png')}}" alt=""><span><em id="copyright-year"></em> &copy; Gatil Neway</span>
                </p>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 rodape2">
                @include('includes.social')
            </div>
        </div>
    </footer>
</div>
<!--JS-->
<script src="{{URL::asset('js/jquery.js')}}"></script>
<script src="{{URL::asset('js/jquery-migrate-1.2.1.min.js')}}"></script>
<script src="{{URL::asset('js/superfish.js')}}"></script>
<script src="{{URL::asset('js/jquery.easing.1.3.js')}}"></script>
<script src="{{URL::asset('js/jquery.mobilemenu.js')}}"></script>
<script src="{{URL::asset('js/jquery.ui.totop.js')}}"></script>
<script src="{{URL::asset('js/jquery.equalheights.js')}}"></script>
<script src="{{URL::asset('js/bootstrap.min.js')}}"></script>
<script src="{{URL::asset('js/tm-scripts.js')}}"></script>
<script src="{{URL::asset('js/scripts.js')}}"></script>

@yield('scripts')
</body>
</html>

resources/views/menu.blade.php
<!--header-->
<header id="topo">
    <div class="container">
        <a href="{{route('index')}}"><img src="{{URL::asset('img/topo.png')}}" alt="" class="img-responsive"></a>
        <div class="clearfix"></div>
    </div>
</header>
<header id="menu">
    <div class="container">
        <nav class="navbar navbar-default navbar-static-top tm_navbar clearfix" role="navigation">
            <ul class="nav sf-menu clearfix">
                <li class="active menu home"><a href="{{route('index')}}">home</a></li>
                <li class="menu sobre"><a href="{{route('site.sobre')}}">sobre</a></li>
                <li class="sub-menu menu nossos_gatos"><a href="{{route('site.nossos_gatos')}}">Nossos Gatos</a><span></span>
                    <ul class="submenu">
                        <li><a href="{{route('site.nossos_gatos')}}#matrizes">Matrizes</a></li>
                        <li><a href="{{route('site.nossos_gatos')}}#padreadores">Padreadores</a></li>
                        <li><a href="{{route('site.disponiveis')}}">Disponíveis</a></li>
                    </ul>
                </li>
                <li class="menu disponiveis"><a href="{{route('site.disponiveis')}}">Disponíveis</a></li>
                <li class="menu videos"><a href="{{route('site.videos')}}">vídeos</a></li>
                <li class="menu noticias"><a href="{{route('site.artigos')}}">artigos</a></li>
                <li class="menu acfe"><a href="{{route('site.acfe')}}">ACFe</a></li>
                <li class="menu contato"><a href="{{route('site.contato')}}">contato</a></li>
            </ul>
        </nav>
    </div>
</header>