routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/



/*Site*/
Route::get('/',['as' => 'index', 'uses' => 'SiteController@index']);

Route::group(['as' => 'site.'], function(){
    Route::get('index',['as' => 'index', 'uses' => 'SiteController@index']);
    Route::get('sobre',['as' => 'sobre', 'uses' => 'SiteController@sobre']);
    Route::get('artigos',['as' => 'artigos', 'uses' => 'SiteController@artigos']);
    Route::get('artigo/{slug}',['as' => 'artigo', 'uses' => 'SiteController@artigo']);
    Route::get('contato',['as' => 'contato', 'uses' => 'SiteController@contato']);
    Route::post('contato_enviar',['as' => 'contato_enviar', 'uses' => 'SiteController@contato_enviar']);
    Route::get('nossos_gatos',['as' => 'nossos_gatos', 'uses' => 'SiteController@nossos_gatos']);
    Route::get('disponiveis',['as' => 'disponiveis', 'uses' => 'SiteController@disponiveis']);
    Route::get('videos',['as' => 'videos', 'uses' => 'SiteController@videos']);
    Route::get('acfe',['as' => 'acfe', 'uses' => 'SiteController@acfe']);

    Route::get('login',['as' => 'login', 'uses' => 'SiteController@login']);
    Route::get('logout',['as' => 'logout', 'uses' => 'SiteController@logout']);

    Route::get('teste',['as' => 'teste', 'uses' => 'SiteController@teste']);
});

/*Admin*/
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['web','auth']], function(){
    Route::get('/',['as' => 'index', 'uses' => 'AdminHomeController@index']);
    Route::get('home',['as' => 'home', 'uses' => 'AdminHomeController@index']);

    Route::get('banners',['as' => 'banners.index', 'uses' => 'AdminBannersController@index']);
    Route::get('banners/novo',['as' => 'banners.novo', 'uses' => 'AdminBannersController@novo']);
    Route::get('banners/editar/{id}',['as' => 'banners.editar', 'uses' => 'AdminBannersController@editar']);
    Route::post('banners/salvar',['as' => 'banners.salvar', 'uses' => 'AdminBannersController@salvar']);
    Route::post('banners/atualizar/{id}',['as' => 'banners.atualizar', 'uses' => 'AdminBannersController@atualizar']);

    Route::get('fotos_categorias',['as' => 'fotos_categorias.index', 'uses' => 'AdminFotosCategoriasController@index']);
    Route::get('fotos_categorias/novo',['as' => 'fotos_categorias.novo', 'uses' => 'AdminFotosCategoriasController@novo']);
    Route::get('fotos_categorias/editar/{id}',['as' => 'fotos_categorias.editar', 'uses' => 'AdminFotosCategoriasController@editar']);
    Route::post('fotos_categorias/salvar',['as' => 'fotos_categorias.salvar', 'uses' => 'AdminFotosCategoriasController@salvar']);
    Route::post('fotos_categorias/atualizar/{id}',['as' => 'fotos_categorias.atualizar', 'uses' => 'AdminFotosCategoriasController@atualizar']);
    Route::get('fotos_categorias/delete/{id}',['as' => 'fotos_categorias.delete', 'uses' => 'AdminFotosCategoriasController@delete']);

    Route::get('fotos/{foto_categoria_id}',['as' => 'fotos.index', 'uses' => 'AdminFotosController@index']);
    Route::get('fotos/novo/{foto_categoria_id}',['as' => 'fotos.novo', 'uses' => 'AdminFotosController@novo']);
    Route::get('fotos/novo2/{foto_categoria_id}',['as' => 'fotos.novo2', 'uses' => 'AdminFotosController@novo2']);
    Route::get('fotos/editar/{id}',['as' => 'fotos.editar', 'uses' => 'AdminFotosController@editar']);
    Route::post('fotos/salvar/{foto_categoria_id}',['as' => 'fotos.salvar', 'uses' => 'AdminFotosController@salvar']);
    Route::post('fotos/salvar2/{foto_categoria_id}',['as' => 'fotos.salvar2', 'uses' => 'AdminFotosController@salvar2']);
    Route::post('fotos/atualizar/{id}',['as' => 'fotos.atualizar', 'uses' => 'AdminFotosController@atualizar']);
    Route::get('fotos/delete/{id}',['as' => 'fotos.delete', 'uses' => 'AdminFotosController@delete']);

    Route::get('artigos',['as' => 'artigos.index', 'uses' => 'AdminNoticiasController@index']);
    Route::get('artigos/novo',['as' => 'artigos.novo', 'uses' => 'AdminNoticiasController@novo']);
    Route::get('artigos/editar/{id}',['as' => 'artigos.editar', 'uses' => 'AdminNoticiasController@editar']);
    Route::post('artigos/salvar',['as' => 'artigos.salvar', 'uses' => 'AdminNoticiasController@salvar']);
    Route::post('artigos/atualizar/{id}',['as' => 'artigos.atualizar', 'uses' => 'AdminNoticiasController@atualizar']);
    Route::get('artigos/delete/{id}',['as' => 'artigos.delete', 'uses' => 'AdminNoticiasController@delete']);

    Route::get('paginas',['as' => 'paginas.index', 'uses' => 'AdminPaginasController@index']);
    Route::get('paginas/novo',['as' => 'paginas.novo', 'uses' => 'AdminPaginasController@novo']);
    Route::get('paginas/editar/{id}',['as' => 'paginas.editar', 'uses' => 'AdminPaginasController@editar']);
    Route::post('paginas/salvar',['as' => 'paginas.salvar', 'uses' => 'AdminPaginasController@salvar']);
    Route::post('paginas/atualizar/{id}',['as' => 'paginas.atualizar', 'uses' => 'AdminPaginasController@atualizar']);
    Route::get('paginas/delete/{id}',['as' => 'paginas.delete', 'uses' => 'AdminPaginasController@delete']);

    Route::get('paginas_textos/{pagina_id}',['as' => 'paginas_textos.index', 'uses' => 'AdminPaginasTextosController@index']);
    Route::get('paginas_textos/novo/{pagina_id}',['as' => 'paginas_textos.novo', 'uses' => 'AdminPaginasTextosController@novo']);
    Route::get('paginas_textos/editar/{id}',['as' => 'paginas_textos.editar', 'uses' => 'AdminPaginasTextosController@editar']);
    Route::post('paginas_textos/salvar/{pagina_id}',['as' => 'paginas_textos.salvar', 'uses' => 'AdminPaginasTextosController@salvar']);
    Route::post('paginas_textos/atualizar/{id}',['as' => 'paginas_textos.atualizar', 'uses' => 'AdminPaginasTextosController@atualizar']);
    Route::get('paginas_textos/delete/{id}',['as' => 'paginas_textos.delete', 'uses' => 'AdminPaginasTextosController@delete']);

    Route::get('colaboradores',['as' => 'colaboradores.index', 'uses' => 'AdminColaboradoresController@index']);
    Route::get('colaboradores/novo',['as' => 'colaboradores.novo', 'uses' => 'AdminColaboradoresController@novo']);
    Route::get('colaboradores/editar/{id}',['as' => 'colaboradores.editar', 'uses' => 'AdminColaboradoresController@editar']);
    Route::post('colaboradores/salvar',['as' => 'colaboradores.salvar', 'uses' => 'AdminColaboradoresController@salvar']);
    Route::post('colaboradores/atualizar/{id}',['as' => 'colaboradores.atualizar', 'uses' => 'AdminColaboradoresController@atualizar']);
    Route::get('colaboradores/delete/{id}',['as' => 'colaboradores.delete', 'uses' => 'AdminColaboradoresController@delete']);

    Route::get('depoimentos',['as' => 'depoimentos.index', 'uses' => 'AdminDepoimentosController@index']);
    Route::get('depoimentos/novo',['as' => 'depoimentos.novo', 'uses' => 'AdminDepoimentosController@novo']);
    Route::get('depoimentos/editar/{id}',['as' => 'depoimentos.editar', 'uses' => 'AdminDepoimentosController@editar']);
    Route::post('depoimentos/salvar',['as' => 'depoimentos.salvar', 'uses' => 'AdminDepoimentosController@salvar']);
    Route::post('depoimentos/atualizar/{id}',['as' => 'depoimentos.atualizar', 'uses' => 'AdminDepoimentosController@atualizar']);
    Route::get('depoimentos/delete/{id}',['as' => 'depoimentos.delete', 'uses' => 'AdminDepoimentosController@delete']);

    Route::get('users',['as' => 'users.index', 'uses' => 'AdminUsersController@index']);
    Route::get('users/novo',['as' => 'users.novo', 'uses' => 'AdminUsersController@novo']);
    Route::get('users/editar/{id}',['as' => 'users.editar', 'uses' => 'AdminUsersController@editar']);
    Route::post('users/salvar',['as' => 'users.salvar', 'uses' => 'AdminUsersController@salvar']);
    Route::post('users/atualizar/{id}',['as' => 'users.atualizar', 'uses' => 'AdminUsersController@atualizar']);
    Route::get('users/senha_editar/{id}',['as' => 'users.senha_editar', 'uses' => 'AdminUsersController@senha_editar']);
    Route::post('users/senha_atualizar/{id}',['as' => 'users.senha_atualizar', 'uses' => 'AdminUsersController@senha_atualizar']);
    Route::get('users/delete/{id}',['as' => 'users.delete', 'uses' => 'AdminUsersController@delete']);
});

/*Auth*/
Route::group(['prefix' => 'auth', 'as' => 'auth.','middleware' => ['web']], function() {
    Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
    Route::post('login', ['as' => 'login.post', 'uses' => 'Auth\LoginController@login']);
    Route::get('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);
});

/*Exibe as SQL's executadas*/
#Event::listen('Illuminate\Database\Events\QueryExecuted', function ($query) {var_dump($query->sql);var_dump($query->bindings);var_dump($query->time);});

app/Foto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Foto extends Model
{
    protected $fillable = [
        'foto_categoria_id',
        'legenda',
        'arquivo',
    ];

    public function fotoCategoria()
    {
        return $this->belongsTo('App\FotoCategoria');
    }
}

resources/views/admin/fotos/editar.blade.php
@extends('admin')

@section('content')

    <div class="container">
        <h3>@if(!empty($botoes['titulo']))Fotos - @endif<strong>{{$foto_categoria->nome}}</strong></h3>

        <br>
        <a href="{{ route('admin.fotos.index',['foto_categoria_id' => $foto_categoria_id]) }}" class="btn btn-default">Voltar</a>
        <br><br>

        @include('errors.mensagens')

        {!! Form::model($foto, ['route' => ['admin.fotos.atualizar', $foto->id], 'class' => 'form']) !!}

        @include('admin.fotos.form')

        {!! Form::close() !!}

    </div>

@endsection

resources/views/admin/fotos/form.blade.php
{!! Form::token() !!}

@if(!empty($botoes['titulo']))
    <div class="form-group input-group">
        {!! Form::label('arquivo','Imagem:') !!}
        {!! Form::text('arquivo', null, ['class' => 'form-control required']) !!}
    </div>
@else
    <div class="form-group">
        {!! Form::label('arquivo','Vídeo:') !!}
        {!! Form::text('arquivo', null, ['class' => 'form-control required']) !!}
    </div>
@endif

<div class="form-group">
    {!! Form::label('legenda','Legenda:') !!}
    {!! Form::text('legenda', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::submit('Salvar', ['class' => 'btn btn-primary']) !!}
</div>

@section('scripts')
    @if(!empty($botoes['titulo']))
        @include('includes.filemanager')
        <script>
            $(function(){
                filemanager_abrir('arquivo');
            });
        </script>
    @endif
    @include('includes.validate')
@endsection

resources/views/admin/fotos/index.blade.php
@extends('admin')

@section('content')

<div class="container">
    <h3>@if(!empty($botoes['titulo'])) Fotos - @endif<strong>{{$foto_categoria->nome}}</strong></h3>

    <br>
    <a href="{{ route('admin.fotos.novo2',['id' => $foto_categoria_id]) }}" class="btn btn-default">{{$botoes['novo']}}</a>
    @if(!empty($botoes['voltar']))
    <a href="{{ route('admin.fotos_categorias.index') }}" class="btn btn-default">{{$botoes['voltar']}}</a>
    @endif
    <br><br>

    <table class="table table-striped">
        <thead>
        <tr>
            <th>{{$botoes['titulo2']}}</th>
            <th>Legenda</th>
            <th width="15%">Ação</th>
        </tr>
        </thead>
        <tbody>
        @foreach($fotos as $v)
        <tr>
            <td>
                @if(strpos($v->arquivo,'youtube') === false)
                    {!! Thumb::img($v->arquivo) !!}
                @else
                    {!! Youtube::thumb($v->arquivo,'mq') !!}
                @endif
            </td>
            <td>{{$v->legenda}}</td>
            <td>
                <a href="{{ route('admin.fotos.editar',['id' => $v->id]) }}" class="btn btn-default btn-xs">editar</a>
                <a href="{{ route('admin.fotos.delete',['id' => $v->id]) }}" class="btn btn-danger btn-xs delete">excluir</a>
            </td>
        </tr>
        @endforeach
        </tbody>
    </table>

    {!! $fotos->render() !!}
</div>

@endsection

@section('scripts')
    @include('includes.delete_alert')
@endsection

resources/views/admin/fotos/novo.blade.php
@extends('admin')

@section('content')

    <div class="container">
        <h3>Fotos - <strong>{{$foto_categoria->nome}}</strong></h3>

        <br>
        <a href="{{ route('admin.fotos.index',['foto_categoria_id' => $foto_categoria->id]) }}" class="btn btn-default">Voltar</a>
        <br><br>

        <div id='fotosList'>
            <table class='fotosEditor table table-striped'>
                <thead>
                <tr>
                    <th width="50%">Fotos</th>
                    <th width="45%">Legenda</th>
                    <th width="5%"></th>
                </tr>
                </thead>
                <tbody data-bind="foreach: fotos">
                <tr>
                    <td>
                        <div class="form-group input-group">
                        <input class="form-control" data-bind='value: arquivo, attr:{"id":"foto"+$index()}' />
                        <span class="input-group-btn">
                            <a data-bind='click:function(){$parent.filemanager_abrir2("foto"+$index())}' class="btn btn-default filemanager-btn" target="_blank">Selecionar Imagem</a>
                        </span>
                        </div>
                    </td>
                    <td>
                        <input class="form-control" data-bind='value: legenda' />
                    </td>
                    <td>
                        <div><a href='#' data-bind='click: $root.removeFoto' class="btn btn-danger btn-xs"><i class="fa fa-trash-o" aria-hidden="true"></i> remover</a></div>
                    </td>
                </tr>
                </tbody>
            </table>
            <p>
                <button data-bind='click: save' class="btn btn-sx btn-primary">Salvar</button>
                <button data-bind='click: addFoto' class="btn btn-sx btn-warning"><i class="fa fa-plus-circle" aria-hidden="true"></i> Nova Fotos</button>
                <span class="ajax-load" style="display: none;">
                    <img src="{{URL::asset('img/ajax_load.gif')}}" alt="">
                    <strong>Salvando, aguarde!</strong>
                </span>
            </p>

            {!! Form::open(['url' => '/admin/fotos/salvar/'.$foto_categoria_id, 'method' => 'post', 'class' => 'form']) !!}
            <input type="hidden" name="fotos" id="fotos">
            {!! Form::close() !!}

        </div>
    </div>
@endsection
@section('scripts')
    @include('includes.filemanager')
    <script src="{{ URL::asset('js/knockoutjs/knockout-3.4.0.js') }}"></script>
    <script>
        $(function(){
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            var initialData = [
                {id:"", foto_categoria_id:"{{$foto_categoria->id}}", legenda:"", arquivo: ""},
                {id:"", foto_categoria_id:"{{$foto_categoria->id}}", legenda:"", arquivo: ""},
                {id:"", foto_categoria_id:"{{$foto_categoria->id}}", legenda:"", arquivo: ""},
                {id:"", foto_categoria_id:"{{$foto_categoria->id}}", legenda:"", arquivo: ""},
                {id:"", foto_categoria_id:"{{$foto_categoria->id}}", legenda:"", arquivo: ""}
            ];

            var FotosModel = function(fotos) {
                var self = this;
                self.fotos = ko.observableArray(ko.utils.arrayMap(fotos, function(foto) {
                    return {
                        id: foto.id,
                        foto_categoria_id: foto.foto_categoria_id,
                        legenda: foto.legenda,
                        arquivo: foto.arquivo
                    };
                }));

                self.filemanager_abrir2 = function(id){
                    open_popup('/js/filemanager/dialog.php?type=1&popup=1&field_id='+id+'&relative_url=1&sort_by=date&descending=1');
                };

                self.foto_categoria = ko.observable({{$foto_categoria_id}});
                self.arquivo = ko.observable();
                self.legenda = ko.observable();

                self.addFoto = function() {
                    self.fotos.push({
                        id: "",
                        foto_categoria_id: self.foto_categoria(),
                        arquivo: self.arquivo(),
                        legenda: self.legenda()
                    });
                };

                self.removeFoto = function(foto) {
                    var confirma = confirm('Deseja excluir esta foto?');
                    if (confirma) {
                        self.fotos.remove(foto);
                    }
                };

                self.save = function() {
                    $('.ajax-load').show();
                    /*var valores = JSON.stringify(ko.toJS(self.fotos,null,2));
                    console.log(valores);*/
                    var valores = JSON.stringify(ko.toJS(self.fotos));
                    $('#fotos').val(valores);
                    $('form').trigger('submit');
                };

            };

            ko.applyBindings(new FotosModel(initialData));
        });
    </script>

@endsection

resources/views/admin/fotos/novo2.blade.php
@extends('admin')

@section('content')

    <div class="container">
        <h3>@if(!empty($botoes['titulo'])) Fotos - @endif<strong>{{$foto_categoria->nome}}</strong></h3>

        <br>
        <a href="{{ route('admin.fotos.index',['foto_categoria_id' => $foto_categoria_id]) }}" class="btn btn-default">Voltar</a>
        <br><br>

        @include('errors.mensagens')

        {!! Form::open(['route' => ['admin.fotos.salvar2', $foto_categoria_id], 'class' => 'form']) !!}

        @include('admin.fotos.form')

        {!! Form::close() !!}

    </div>

@endsection