routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/



/*Site*/
Route::get('/',['as' => 'index', 'uses' => 'SiteController@index']);

Route::group(['as' => 'site.'], function(){
    Route::get('index',['as' => 'index', 'uses' => 'SiteController@index']);
    Route::get('sobre',['as' => 'sobre', 'uses' => 'SiteController@sobre']);
    Route::get('artigos',['as' => 'artigos', 'uses' => 'SiteController@artigos']);
    Route::get('artigo/{slug}',['as' => 'artigo', 'uses' => 'SiteController@artigo']);
    Route::get('contato',['as' => 'contato', 'uses' => 'SiteController@contato']);
    Route::post('contato_enviar',['as' => 'contato_enviar', 'uses' => 'SiteController@contato_enviar']);
    Route::get('nossos_gatos',['as' => 'nossos_gatos', 'uses' => 'SiteController@nossos_gatos']);
    Route::get('disponiveis',['as' => 'disponiveis', 'uses' => 'SiteController@disponiveis']);
    Route::get('videos',['as' => 'videos', 'uses' => 'SiteController@videos']);
    Route::get('acfe',['as' => 'acfe', 'uses' => 'SiteController@acfe']);

    Route::get('login',['as' => 'login', 'uses' => 'SiteController@login']);
    Route::get('logout',['as' => 'logout', 'uses' => 'SiteController@logout']);

    Route::get('teste',['as' => 'teste', 'uses' => 'SiteController@teste']);
});

/*Admin*/
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['web','auth']], function(){
    Route::get('/',['as' => 'index', 'uses' => 'AdminHomeController@index']);
    Route::get('home',['as' => 'home', 'uses' => 'AdminHomeController@index']);

    Route::get('banners',['as' => 'banners.index', 'uses' => 'AdminBannersController@index']);
    Route::get('banners/novo',['as' => 'banners.novo', 'uses' => 'AdminBannersController@novo']);
    Route::get('banners/editar/{id}',['as' => 'banners.editar', 'uses' => 'AdminBannersController@editar']);
    Route::post('banners/salvar',['as' => 'banners.salvar', 'uses' => 'AdminBannersController@salvar']);
    Route::post('banners/atualizar/{id}',['as' => 'banners.atualizar', 'uses' => 'AdminBannersController@atualizar']);

    Route::get('fotos_categorias',['as' => 'fotos_categorias.index', 'uses' => 'AdminFotosCategoriasController@index']);
    Route::get('fotos_categorias/novo',['as' => 'fotos_categorias.novo', 'uses' => 'AdminFotosCategoriasController@novo']);
    Route::get('fotos_categorias/editar/{id}',['as' => 'fotos_categorias.editar', 'uses' => 'AdminFotosCategoriasController@editar']);
    Route::post('fotos_categorias/salvar',['as' => 'fotos_categorias.salvar', 'uses' => 'AdminFotosCategoriasController@salvar']);
    Route::post('fotos_categorias/atualizar/{id}',['as' => 'fotos_categorias.atualizar', 'uses' => 'AdminFotosCategoriasController@atualizar']);
    Route::get('fotos_categorias/delete/{id}',['as' => 'fotos_categorias.delete', 'uses' => 'AdminFotosCategoriasController@delete']);

    Route::get('fotos/{foto_categoria_id}',['as' => 'fotos.index', 'uses' => 'AdminFotosController@index']);
    Route::get('fotos/novo/{foto_categoria_id}',['as' => 'fotos.novo', 'uses' => 'AdminFotosController@novo']);
    Route::get('fotos/novo2/{foto_categoria_id}',['as' => 'fotos.novo2', 'uses' => 'AdminFotosController@novo2']);
    Route::get('fotos/editar/{id}',['as' => 'fotos.editar', 'uses' => 'AdminFotosController@editar']);
    Route::post('fotos/salvar/{foto_categoria_id}',['as' => 'fotos.salvar', 'uses' => 'AdminFotosController@salvar']);
    Route::post('fotos/salvar2/{foto_categoria_id}',['as' => 'fotos.salvar2', 'uses' => 'AdminFotosController@salvar2']);
    Route::post('fotos/atualizar/{id}',['as' => 'fotos.atualizar', 'uses' => 'AdminFotosController@atualizar']);
    Route::get('fotos/delete/{id}',['as' => 'fotos.delete', 'uses' => 'AdminFotosController@delete']);

    Route::get('artigos',['as' => 'artigos.index', 'uses' => 'AdminNoticiasController@index']);
    Route::get('artigos/novo',['as' => 'artigos.novo', 'uses' => 'AdminNoticiasController@novo']);
    Route::get('artigos/editar/{id}',['as' => 'artigos.editar', 'uses' => 'AdminNoticiasController@editar']);
    Route::post('artigos/salvar',['as' => 'artigos.salvar', 'uses' => 'AdminNoticiasController@salvar']);
    Route::post('artigos/atualizar/{id}',['as' => 'artigos.atualizar', 'uses' => 'AdminNoticiasController@atualizar']);
    Route::get('artigos/delete/{id}',['as' => 'artigos.delete', 'uses' => 'AdminNoticiasController@delete']);

    Route::get('paginas',['as' => 'paginas.index', 'uses' => 'AdminPaginasController@index']);
    Route::get('paginas/novo',['as' => 'paginas.novo', 'uses' => 'AdminPaginasController@novo']);
    Route::get('paginas/editar/{id}',['as' => 'paginas.editar', 'uses' => 'AdminPaginasController@editar']);
    Route::post('paginas/salvar',['as' => 'paginas.salvar', 'uses' => 'AdminPaginasController@salvar']);
    Route::post('paginas/atualizar/{id}',['as' => 'paginas.atualizar', 'uses' => 'AdminPaginasController@atualizar']);
    Route::get('paginas/delete/{id}',['as' => 'paginas.delete', 'uses' => 'AdminPaginasController@delete']);

    Route::get('paginas_textos/{pagina_id}',['as' => 'paginas_textos.index', 'uses' => 'AdminPaginasTextosController@index']);
    Route::get('paginas_textos/novo/{pagina_id}',['as' => 'paginas_textos.novo', 'uses' => 'AdminPaginasTextosController@novo']);
    Route::get('paginas_textos/editar/{id}',['as' => 'paginas_textos.editar', 'uses' => 'AdminPaginasTextosController@editar']);
    Route::post('paginas_textos/salvar/{pagina_id}',['as' => 'paginas_textos.salvar', 'uses' => 'AdminPaginasTextosController@salvar']);
    Route::post('paginas_textos/atualizar/{id}',['as' => 'paginas_textos.atualizar', 'uses' => 'AdminPaginasTextosController@atualizar']);
    Route::get('paginas_textos/delete/{id}',['as' => 'paginas_textos.delete', 'uses' => 'AdminPaginasTextosController@delete']);

    Route::get('colaboradores',['as' => 'colaboradores.index', 'uses' => 'AdminColaboradoresController@index']);
    Route::get('colaboradores/novo',['as' => 'colaboradores.novo', 'uses' => 'AdminColaboradoresController@novo']);
    Route::get('colaboradores/editar/{id}',['as' => 'colaboradores.editar', 'uses' => 'AdminColaboradoresController@editar']);
    Route::post('colaboradores/salvar',['as' => 'colaboradores.salvar', 'uses' => 'AdminColaboradoresController@salvar']);
    Route::post('colaboradores/atualizar/{id}',['as' => 'colaboradores.atualizar', 'uses' => 'AdminColaboradoresController@atualizar']);
    Route::get('colaboradores/delete/{id}',['as' => 'colaboradores.delete', 'uses' => 'AdminColaboradoresController@delete']);

    Route::get('depoimentos',['as' => 'depoimentos.index', 'uses' => 'AdminDepoimentosController@index']);
    Route::get('depoimentos/novo',['as' => 'depoimentos.novo', 'uses' => 'AdminDepoimentosController@novo']);
    Route::get('depoimentos/editar/{id}',['as' => 'depoimentos.editar', 'uses' => 'AdminDepoimentosController@editar']);
    Route::post('depoimentos/salvar',['as' => 'depoimentos.salvar', 'uses' => 'AdminDepoimentosController@salvar']);
    Route::post('depoimentos/atualizar/{id}',['as' => 'depoimentos.atualizar', 'uses' => 'AdminDepoimentosController@atualizar']);
    Route::get('depoimentos/delete/{id}',['as' => 'depoimentos.delete', 'uses' => 'AdminDepoimentosController@delete']);

    Route::get('users',['as' => 'users.index', 'uses' => 'AdminUsersController@index']);
    Route::get('users/novo',['as' => 'users.novo', 'uses' => 'AdminUsersController@novo']);
    Route::get('users/editar/{id}',['as' => 'users.editar', 'uses' => 'AdminUsersController@editar']);
    Route::post('users/salvar',['as' => 'users.salvar', 'uses' => 'AdminUsersController@salvar']);
    Route::post('users/atualizar/{id}',['as' => 'users.atualizar', 'uses' => 'AdminUsersController@atualizar']);
    Route::get('users/senha_editar/{id}',['as' => 'users.senha_editar', 'uses' => 'AdminUsersController@senha_editar']);
    Route::post('users/senha_atualizar/{id}',['as' => 'users.senha_atualizar', 'uses' => 'AdminUsersController@senha_atualizar']);
    Route::get('users/delete/{id}',['as' => 'users.delete', 'uses' => 'AdminUsersController@delete']);
});

/*Auth*/
Route::group(['prefix' => 'auth', 'as' => 'auth.','middleware' => ['web']], function() {
    Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
    Route::post('login', ['as' => 'login.post', 'uses' => 'Auth\LoginController@login']);
    Route::get('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);
});

/*Exibe as SQL's executadas*/
#Event::listen('Illuminate\Database\Events\QueryExecuted', function ($query) {var_dump($query->sql);var_dump($query->bindings);var_dump($query->time);});

resources/views/site/acfe.blade.php
@extends('layout')

@section('content')
    <div class="global indent gallery-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 artigos">
                    <h2 class="normal">{{$texto[0]['nome']}}</h2>
                    {!! $texto[0]['texto'] !!}
                    <br><br>

                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script>
        $(function(){
            menu('acfe');
        });
    </script>
@endsection

resources/views/site/artigo.blade.php
@extends('layout')

@section('content')
    <div class="global indent gallery-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 artigos">
                    <h2>{{$artigo->titulo}}</h2>
                    <time datetime="{{substr($artigo->created_at,0,10)}}">{{Formata::date(substr($artigo->created_at,0,10),'.')}}</time>
                    @if(!empty($artigo->arquivo))
                    <figure><img src="{{URL::asset($artigo->arquivo)}}" alt="" class="img-responsive"></figure>
                    @endif
                    <br>
                    <div class="texto">{!! $artigo->texto !!}</div>
                    <br><br>

                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script>
        $(function(){
            menu('noticias');
        });
    </script>
@endsection

resources/views/site/artigos.blade.php
@extends('layout')

@section('content')
    <div class="global indent gallery-box">
        <div class="container">
            <h2>Últimos Artigos</h2>
            <div class="row">

                @foreach($artigos as $v)
                <div class="col-lg-4 col-md-4 col-sm-4">
                    <div class="thumb-pad5 maxheight">
                        <div class="thumbnail">
                            <figure>
                                @if(!empty($v->arquivo))
                                    <a href="{{route('site.artigo',['slug'=>$v->slug])}}"><img src="{{URL::asset($v->arquivo)}}" alt=""></a>
                                @else
                                    <a href="{{route('site.artigo',['slug'=>$v->slug])}}"><img src="{{URL::asset('img/img-vazio.png')}}" alt=""></a>
                                @endif
                            </figure>
                            <div class="caption">
                                <time datetime="{{substr($v->created_at,0,10)}}">{{Formata::date(substr($v->created_at,0,10),'.')}}</time>
                                <a href="{{route('site.artigo',['slug'=>$v->slug])}}" class="description">{{$v->titulo}}</a>
                                <p>{{Texto::resumo($v->texto)}}...</p>
                                <a href="{{route('site.artigo',['slug'=>$v->slug])}}" class="btn-default btn1">mais...</a>
                            </div>
                        </div>
                    </div>
                </div>
                @endforeach

                <div class="clearfix"></div>
                <div class="col-lg-8 col-md-8 col-sm-8 centre-box">
                    <h2>Mais Artigos</h2>
                    @foreach($artigos2 as $v)
                    <time datetime="{{substr($v->created_at,0,10)}}"><a href="{{route('site.artigo',['slug'=>$v->slug])}}">{{Formata::date(substr($v->created_at,0,10),'.')}}</a></time>
                    <br>
                    <a href="{{route('site.artigo',['slug'=>$v->slug])}}" class="title">{{$v->titulo}}</a>
                    <p>{{Texto::resumo($v->texto)}}...</p>
                    @endforeach
                    <div>{!! $artigos2->render() !!}</div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4">
                    <h2>Arquivo</h2>
                    <ul class="list3">
                        <li><a href="#">2016</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script>
        $(function(){
            menu('noticias');
        });
    </script>
@endsection

resources/views/site/contato.blade.php
@extends('layout')

@section('content')
    <div class="global indent">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <figure class="map">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d1213.0411054249778!2d-40.33056513173345!3d-20.319702103725255!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xc018fc0359dfb766!2sGatil+Neway!5e0!3m2!1spt-BR!2sbr!4v1474506600227" style="border:0" allowfullscreen></iframe>
                    </figure>
                </div>
            </div>
        </div>
        <div class="formBox">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <h2>Endereço</h2>
                        <div class="info">
                            <h3>Endereço:</h3>
                            <p>
                                Cidade de Vitória - Espírito Santo
                            </p>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <h2>&nbsp;</h2>
                        <div class="info">
                            <h3>Telefones:</h3>
                            <p>
                                (27) 3233-3951<br>
                                (27) 99292-3399
                                <span><img src="{{URL::asset('img/ico_claro.png')}}" alt="Claro" title="Claro" style="width: 24px;"></span>
                                <span><img src="{{URL::asset('img/ico_whatsapp.png')}}" alt="Whatsapp" title="Whatsapp" style="width: 24px;"></span>
                            </p>
                        </div>
                    </div>
                    {{--<div class="col-lg-8 col-md-8 col-sm-8">
                        <a id="formulario"></a><h2>Formulário</h2>
                        <form id="contact-form" action="{{route('site.contato_enviar')}}" method="post">
                            {!! Form::token() !!}

                            @if(!empty(Session::get('enviado')))
                            <div class="btns">
                                <p>{{Session::get('enviado')}}</p>
                            </div>
                            <br style="clear: both">
                            @endif

                            <div class="holder">
                                <div class="form-div-1 clearfix">
                                    <p>Nome*</p>
                                    <label class="name">
                                        <input name="nome" type="text" placeholder="" class="required" />
                                        <span class="error-message"></span>
                                    </label>
                                </div>
                                <div class="form-div-2 clearfix">
                                    <p>E-mail*</p>
                                    <label class="email">
                                        <input name="email" type="text" placeholder="" class="required email" />
                                        <span class="error-message"></span>
                                    </label>
                                </div>
                                <div class="form-div-3 clearfix">
                                    <p>Telefone</p>
                                    <label class="phone notRequired">
                                        <input name="telefone" type="text" placeholder=""/>
                                        <span class="error-message"></span>
                                    </label>
                                </div>
                            </div>
                            <div class="form-div-4 clearfix">
                                <p>Mensagem*</p>
                                <label class="message">
                                    <textarea name="mensagem" placeholder="" class="required"></textarea>
                                    <span class="error-message"></span>
                                </label>
                            </div>
                            <div class="btns">
                                <button type="submit" class="btn btn-default btn1 contato-btn">enviar</button>
                                <p>* campos obrigatórios</p>
                            </div>
                        </form>
                    </div>--}}
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script src="{{ URL::asset('js/jquery-validation/jquery.validate.min.js') }}"></script>
    <script src="{{ URL::asset('js/jquery-validation/additional-methods.min.js') }}"></script>
    <script src="{{ URL::asset('js/jquery-validation/localization/messages_pt_BR.min.js') }}"></script>
    <script>
        $(function(){
            menu('contato');
            var maps_id = ".map";
            $('.map iframe').css("pointer-events", "none");
            $(maps_id).click(function () {
                $('.map iframe').css("pointer-events", "auto");
            });

            $(maps_id).mouseleave(function() {
                $('.map iframe').css("pointer-events", "none");
            });
            $.validator.addClassRules({
                required: {
                    required: true
                },
                minlength: {
                    minlength: 3
                },
                currency: {
                    required: true
                },
                email:{
                    email: true
                }
            });
            $('#contact-form').validate({
                //debug: true,
                errorClass:'error-message',
                validClass:'success',
                errorElement:'label',
                highlight: function (element, errorClass, validClass) {
                    $(element).parents("div.form-div-4").addClass("error-message has-error");

                },
                unhighlight: function (element, errorClass, validClass) {
                    $(element).parents(".error-message").removeClass("error-message has-error");
                }
            });
        });
    </script>
@endsection

resources/views/site/contato_enviar.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<strong>Nome:</strong> {{$nome}}<br>
<strong>E-mail:</strong> {{$email}}<br>
<strong>Telefone:</strong> {{$telefone}}<br>
<strong>Mensagem:</strong> {!! nl2br($mensagem) !!}<br>
</body>
</html>

resources/views/site/index.blade.php
@extends('layout')

@section('content')
    <div class="global">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="slider">
                        <div class="camera_wrap">
                            @foreach($banners as $v)
                            <div data-src="{{$v->arquivo}}"><div class="camera-caption fadeIn"><p class="title">{{$v->legenda}}</p></div></div>
                            @endforeach
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4">
                    <div class="thumb-pad0">
                        <div class="thumbnail">
                            <figure><img src="{{URL::asset('img/desenho01.png')}}" alt="" style="width:127px"></figure>
                            <div class="caption">
                                <a href="#" class="title">Gatos trazem alegria<br>à nossas vidas <br></a>
                                <p>Os gatos são animais ótimos de convívio, sossegados, independentes, muito carinhosos e higiênicos..</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4">
                    <div class="thumb-pad0">
                        <div class="thumbnail">
                            <figure><img src="{{URL::asset('img/desenho02.png')}}" alt="" style="width:127px"></figure>
                            <div class="caption">
                                <a href="#" class="title">Os gatos fazem você <br>se sentir especial!</a>
                                <p>O gato se contenta em ficar ao seu lado, mesmo enquanto você está ocupado com outras coisas.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4">
                    <div class="thumb-pad0">
                        <div class="thumbnail">
                            <figure><img src="{{URL::asset('img/desenho03.png')}}" alt="" style="width:127px"></figure>
                            <div class="caption">
                                <a href="#" class="title">São divertidos <br>e melhoram seu humor!</a>
                                <p>Os estudos comprovam que pessoas que têm animais de estimação tendem a apresentar e demonstrar menos estresse quando comparadas com aquelas que não têm animais.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="about-box">
                    <div class="col-lg-7 col-md-7 col-sm-12">
                        <h2 class="indent"><span>{{$texto[0]['nome']}}</span></h2>
                        <div class="thumb-pad1">
                            <div class="thumbnail">
                                <figure><img src="{{URL::asset('img/saiba_tudo.jpg')}}" alt="" style="width: 270px;"></figure>
                                <div class="caption">
                                    {!! $texto[0]['texto'] !!}
                                </div>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-12 col-lg-offset-1 pets-box">
                        <h2>Nossos Gatos</h2>
                        <ul class="list2">

                            @foreach($matrizes as $v)
                                <li>
                                    <figure>
                                        <a href="{{$v->arquivo}}" rel="fotos_{{$v->id}}" class="title" title="{{$v->nome}}">{!!Thumb::img($v->arquivo, 100)!!}</a>
                                    </figure>
                                    <div class="extra-wrap">
                                        <a href="#" class="title" title="{{$v->nome}}">{{$v->nome}}</a>
                                        <p>{{$v->descricao}}</p>
                                    </div>
                                    @foreach($v->fotos as $v2)
                                        <a href="{{$v2->arquivo}}" rel="fotos_{{$v->id}}" class="title {{$v2->classe_css}}" title="{{$v2->legenda}}"></a>
                                    @endforeach
                                </li>
                            @endforeach
                            @foreach($padreadores as $v)
                                <li>
                                    <figure>
                                        <a href="{{$v->arquivo}}" rel="fotos_{{$v->id}}" class="title" title="{{$v->nome}}">{!!Thumb::img($v->arquivo, 100)!!}</a>
                                    </figure>
                                    <div class="extra-wrap">
                                        <a href="#" class="title" title="{{$v->nome}}">{{$v->nome}}</a>
                                        <p>{{$v->descricao}}</p>
                                    </div>
                                    @foreach($v->fotos as $v2)
                                        <a href="{{$v2->arquivo}}" rel="fotos_{{$v->id}}" class="title" title="{{$v2->legenda}}"></a>
                                    @endforeach
                                </li>
                            @endforeach
                        </ul>
                        <a href="{{route('site.nossos_gatos')}}" class="btn-default btn1">mais...</a>
                    </div>
                </div>

                <div class="col-lg-12">
                    <h2 class="indent"><span>Disponíveis</span></h2>
                    <div class="thumb-pad1">
                        <div class="thumbnail">
                            @include('site.fotos_include',['titulo'=> '', 'valores' => $disponiveis, 'ancora' => 'disponiveis', 'col_tamanho' => 4])
                            <p>
                                <span>Todos são alimentados com ração Premier.</span><br>
                                <a href="http://www.premierpet.com.br" target="_blank" style="display: inline-block;"><img src="{{URL::asset('img/premier.png')}}" alt=""></a>
                            </p>
                            <a href="{{route('site.disponiveis')}}" class="btn-default btn1">mais disponíveis...</a>
                        </div>
                    </div>
                </div>

                <div class="col-lg-12">
                    <h2 class="indent"><span>{{$texto[1]['nome']}}</span></h2>
                    <div class="thumb-pad1">
                        <div class="thumbnail">
                            <figure><img src="{{URL::asset('img/nossos_servicos.jpg')}}" alt="" style="width: 270px;"></figure>
                            <div class="caption">

                                {!! $texto[1]['texto'] !!}

                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-12 news-box">
                    <h2>Últimos Vídeos</h2>
                    <div class="row">
                        @foreach($videos as $v)
                            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                                <p>
                                    {!! Youtube::embed($v->arquivo,true,'100%') !!}
                                </p>
                            </div>
                        @endforeach
                        <br style="clear: both">
                        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                            <a href="{{route('site.videos')}}" class="btn-default btn1">mais...</a>
                        </div>
                    </div>
                </div>

                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 news-box">
                    <h2>Últimos Artigos</h2>
                    <div class="row">
                        @foreach($artigos as $v)
                        <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                            <time datetime="{{substr($v->created_at,0,10)}}"><a href="{{route('site.artigo',['slug'=>$v->slug])}}">{{Formata::date(substr($v->created_at,0,10),'.')}}</a></time>
                            <p>
                                <a href="{{route('site.artigo',['slug'=>$v->slug])}}" class="title">{{$v->titulo}}</a><br>
                                {!! Texto::resumo($v->texto, 80) !!}...
                            </p>
                        </div>
                        @endforeach
                        <br style="clear: both">
                        <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                            <a href="{{route('site.artigos')}}" class="btn-default btn1">mais...</a>
                        </div>
                    </div>

                </div>
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 pets-box">
                    <div id="fb-root"></div>
                    <script>(function(d, s, id) {
                            var js, fjs = d.getElementsByTagName(s)[0];
                            if (d.getElementById(id)) return;
                            js = d.createElement(s); js.id = id;
                            js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.7";
                            fjs.parentNode.insertBefore(js, fjs);
                        }(document, 'script', 'facebook-jssdk'));</script>
                    <div class="fb-page" data-href="https://www.facebook.com/gneway/?fref=ts" data-tabs="timeline" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/gneway/?fref=ts" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/gneway/?fref=ts">Gatil Neway</a></blockquote></div>
                </div>
            </div>
        </div>
    </div>
    <br>
@endsection

@section('scripts')
    @include('includes.fancybox')
    <link rel="stylesheet" href="{{URL::asset('css/camera.css')}}">
    <script src="{{URL::asset('js/camera.js')}}"></script>
    <script>
        $(function(){
            $('.camera_wrap').camera();
            menu('home');
        });
    </script>
@endsection

resources/views/site/nossos_gatos.blade.php
@extends('layout')

@section('content')
    <div class="global indent">
        <!--content-->
        <div class="container">
            <h2>Nossos Gatos</h2>
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 services-box">
                    @include('site.fotos_include',['titulo'=> 'Matrizes', 'valores' => $matrizes, 'ancora' => 'matrizes'])
                </div>

                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 services-box">
                    @include('site.fotos_include',['titulo'=> 'Padreadores', 'valores' => $padreadores, 'ancora' => 'padreadores'])
                </div>

                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 services-box">
                    @include('site.fotos_include',['titulo'=> 'Disponíveis (<a href="'.route('site.disponiveis').'#comprar">Clique aqui para transferência de valores</a>)', 'valores' => $disponiveis, 'ancora' => 'disponiveis'])
                </div>

                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 services-box">
                    @include('site.fotos_include',['titulo'=> 'Galeria de Fotos', 'valores' => $galeria, 'ancora' => 'galeria'])
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    @include('includes.fancybox')
    <script>
        $(function(){
            menu('nossos_gatos');
        });
    </script>
@endsection